create database ChildDevSchool
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
use ChildDevSchool;

create table user
(
id INT NOT NULL AUTO_INCREMENT,
username VARCHAR(20) NOT NULL,
auth_key VARCHAR(32),
password_hash VARCHAR (64),
password_reset_token VARCHAR (64),
status INTEGER,
created_at INTEGER,
updated_at INTEGER,
CONSTRAINT pk_u PRIMARY KEY (id)
);

create table Ancestors
(
A INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR (64),
NUMBER_PHONE VARCHAR (20),
EMAIL VARCHAR(64),
fk_u INT ,
CONSTRAINT pk_a PRIMARY KEY (A),
CONSTRAINT FOREIGN KEY (fk_u) REFERENCES user(id)
);

create table Courses
(C INT NOT NULL AUTO_INCREMENT,
 NAME VARCHAR (64),
 DURATION VARCHAR (64),
 PLACE VARCHAR (64),
 COST INT,
 CONSTRAINT pk_c PRIMARY KEY (C)
);

create table Teachers
(
T INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR (64),
NUMBER_PHONE VARCHAR (20),
EMAIL VARCHAR(64),
QUALIFICATION VARCHAR(256),
fk_C INT,
fk_u INT,
CONSTRAINT pk_t PRIMARY KEY (T),
CONSTRAINT FOREIGN KEY (fk_u) REFERENCES user(id),
CONSTRAINT FOREIGN KEY (fk_C) REFERENCES Courses(C)
);

create table Children
(C INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR (64),
NUMBER_PHONE VARCHAR (20),
DATA_OF_BIRTH DATE,
EMAIL VARCHAR (64),
CONSTRAINT pk_C PRIMARY KEY (C)
);

 create table Parents_Children
 (
 PC INT NOT NULL AUTO_INCREMENT,
 fk_PR INT ,
 fk_CH INT ,
 CONSTRAINT pk_PC PRIMARY KEY (PC),
 CONSTRAINT FOREIGN KEY (fk_PR) REFERENCES Ancestors(A),
 CONSTRAINT FOREIGN KEY (fk_CH) REFERENCES Children(C)
 );


create table Requests
(R INT NOT NULL AUTO_INCREMENT,
NAME_PARENT VARCHAR(64),
NUMBER_PHONE VARCHAR(20),
EMAIL VARCHAR (64),
STATUS INT(1),
fk_c INT ,
CONSTRAINT pk_r PRIMARY KEY (R),
CONSTRAINT FOREIGN KEY (fk_c) REFERENCES Courses(C)
);

create table Collectives
(
  C INT NOT NULL AUTO_INCREMENT,
  fk_CH INT,
  fk_CR INT,
  CONSTRAINT pk_G PRIMARY KEY (C),
  CONSTRAINT FOREIGN KEY (fk_CR) REFERENCES Courses(C),
  CONSTRAINT FOREIGN KEY (fk_CH) REFERENCES Children(C)
);

create table Teachers_Courses
(
  TC INT NOT NULL AUTO_INCREMENT,
  fk_T INT ,
  fk_C INT ,
  CONSTRAINT pk_PC PRIMARY KEY (TC),
  CONSTRAINT FOREIGN KEY (fk_T) REFERENCES Teachers(T),
  CONSTRAINT FOREIGN KEY (fk_C) REFERENCES Courses(C)
);


create table Payments
(
  P INT NOT NULL AUTO_INCREMENT,
  DATA_OF_PAYMENT DATE,
  fk_CH INT,
  fk_CR INT,
  COST INT,
  STATUS INT(1),
  CONSTRAINT pk_P PRIMARY KEY (P),
  CONSTRAINT FOREIGN KEY (fk_CH) REFERENCES Children(C),
  CONSTRAINT FOREIGN KEY (fk_CR) REFERENCES Courses(C)
);

create table Reports
(
  R INT NOT NULL AUTO_INCREMENT,
  CONSTRAINT pk_R PRIMARY KEY (R)
);

